services:
  - type: web
    name: mvc-logistica-laravel
    runtime: php # Corrección del entorno para Render
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      touch database/database.sqlite
      php artisan migrate --force --seed
      apache2-foreground
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false # ASÍ ES CORRECTO: Le dice a Render que te pida el valor largo en su página web
      - key: DB_CONNECTION
        value: sqlite
      - key: LOG_CHANNEL
        value: stderr
