services:
  - type: web
    name: mvc-logistica-laravel
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      # Creamos la base de datos limpia en la ruta por defecto de Laravel
      touch database/database.sqlite
      # Ejecutamos las migraciones y los seeders automáticos al arrancar
      php artisan migrate --force --seed
      apache2-foreground
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: IS0cEdO+Oj3KJqevxizKVF7BA8uO6uCdhxRrEtaKFJA=
        sync: false
      - key: DB_CONNECTION
        value: sqlite
      - key: LOG_CHANNEL
        value: stderr